### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by dsfcoll** [bhaskarGyan/nuxt-cache-ssr#11]
I'm ready to implement some of roadmap features
Just need to know if @bhaskarGyan  is still interested

**Comment by bhaskarGyan** [comment]
@VladStepanov Not currently, I haven't archived it in case I decide to revive it but that is a very slim chance since I have moved on to Sveltekit currently.

In case you are interested in implementing the remaining features, I can make you the maintainer.

or you can feel free to fork and modify it to your needs.
